server:
  port: 8081

spring:
  application:
    name: patient-service

kafka:
  bootstrap-servers: localhost:9092
  topic:
    patient-created: patient-created
    patient-updated: patient-updated
    patient-deleted: patient-deleted

jwt:
  secret: dGhpc2lzYXNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbmluaG9zcGl0YWxzeXN0ZW0=
  expiration: 600000

# Enable Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Actuator endpoints for health monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always